### get data users
get http://localhost:2471/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI3LCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNjU4OTM0OTc0LCJleHAiOjE2NTg5MzQ5OTR9.RqCrmREtxkshgD-R-zEWR0C8Ei-on6PH1TZ6TbKsK4I

### register
POST http://localhost:2471/users
Content-Type: application/json

{
    "name": "nanang febri",
    "email": "febrinanang@gmail.com",
    "password": "11223344",
    "confPassword": "11223344",
    "role" : 2
}

### login
POST http://localhost:2471/login
Content-Type: application/json

{
    "email" : "admin@mail.com",
    "password" : "admin"
}

### refresh token
GET http://localhost:2471/token

### logout
DELETE http://localhost:2471/logout

### forgot
put http://localhost:2471/forgot
Content-Type: application/json

{
    "email" : "febrinanang2@gmail.com",
    "password" : "haloa",
    "confPassword" : "haloa"
}

### get data roles
get http://localhost:2471/roles

### post data role
POST http://localhost:2471/roles
Content-Type: application/json

{
    "role_id" : 8,
    "role_name" : "Project Manager"
}

### get data karyawan
GET http://localhost:2471/karyawans


### post data karyawan 
POST http://localhost:2471/karyawans
Content-Type: application/json

{
    "user_id": "3",
    "fullname": "Nina",
    "statuspernikahan": "JandaSelusin",
    "nik": "92873230223232",
    "identitas": "KTP",
    "divisi": "BSO",
    "tanggalmasuk": "",
    "statuskaryawan": "1",
    "email": "iwan@yahoo.com",
    "phone": "089121221333",
    "alamat": "Jl Kantil",
    "posisi": "",
    "site": "",
    "telegram": "",
    "createdby": "",
    "createdate": "",
    "pendidikan": "",
    "institusi": "",
    "tempatlahir": "",
    "tanggallahir": "",
    "status": "",
    "role_trello": "",
    "nikkaryawan": "",
    "jurusan": "",
    "createddby": "",
    "updateat": ""
}

### update data karyawan 
PUT http://localhost:2471/karyawans
Content-Type: application/json

{
    "user_id": "1",
    "fullname": "Karyo Wawan",
    "statuspernikahan": "Duda",
    "nik": "1642957970001246",
    "identitas": "KTP",
    "divisi": "Developer",
    "tanggalmasuk": "",
    "statuskaryawan": "1",
    "email": "wawan@yahoo.com",
    "phone": "089888888888",
    "alamat": "Jl Cantel",
    "posisi": "",
    "site": "",
    "telegram": "",
    "createdby": "",
    "createdate": "",
    "pendidikan": "",
    "institusi": "",
    "tempatlahir": "",
    "tanggallahir": "",
    "status": "",
    "role_trello": "",
    "nikkaryawan": "",
    "jurusan": "",
    "createddby": "",
    "updateat": ""
}

### hapus data karyawan 
PUT http://localhost:2471/karyawan
Content-Type: application/json

{
    "user_id": "1"
}